-- MEDINTERNX DATABASE SETUP
-- Run this entire script once in Supabase SQL Editor.
-- It creates courses, profiles, enrollments and module progress with RLS.

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null,
  duration text not null default '4 weeks',
  level text not null default 'Beginner',
  icon text not null default '📚',
  topics jsonb not null default '[]'::jsonb,
  modules jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  enrolled_at timestamptz not null default now(),
  completed_at timestamptz,
  unique(user_id, course_id)
);

create table if not exists public.module_progress (
  id bigint generated by default as identity primary key,
  enrollment_id bigint not null references public.enrollments(id) on delete cascade,
  module_index integer not null,
  completed boolean not null default false,
  completed_at timestamptz,
  unique(enrollment_id, module_index)
);

alter table public.courses enable row level security;
alter table public.profiles enable row level security;
alter table public.enrollments enable row level security;
alter table public.module_progress enable row level security;

drop policy if exists "courses public read" on public.courses;
create policy "courses public read" on public.courses for select to anon, authenticated using (true);

drop policy if exists "profile own select" on public.profiles;
create policy "profile own select" on public.profiles for select to authenticated using ((select auth.uid()) = id);
drop policy if exists "profile own insert" on public.profiles;
create policy "profile own insert" on public.profiles for insert to authenticated with check ((select auth.uid()) = id);
drop policy if exists "profile own update" on public.profiles;
create policy "profile own update" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "enrollment own select" on public.enrollments;
create policy "enrollment own select" on public.enrollments for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "enrollment own insert" on public.enrollments;
create policy "enrollment own insert" on public.enrollments for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "enrollment own update" on public.enrollments;
create policy "enrollment own update" on public.enrollments for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "progress own select" on public.module_progress;
create policy "progress own select" on public.module_progress for select to authenticated
using (exists (select 1 from public.enrollments e where e.id = enrollment_id and e.user_id = (select auth.uid())));
drop policy if exists "progress own insert" on public.module_progress;
create policy "progress own insert" on public.module_progress for insert to authenticated
with check (exists (select 1 from public.enrollments e where e.id = enrollment_id and e.user_id = (select auth.uid())));
drop policy if exists "progress own update" on public.module_progress;
create policy "progress own update" on public.module_progress for update to authenticated
using (exists (select 1 from public.enrollments e where e.id = enrollment_id and e.user_id = (select auth.uid())))
with check (exists (select 1 from public.enrollments e where e.id = enrollment_id and e.user_id = (select auth.uid())));

insert into public.courses (name,description,duration,level,icon,topics,modules) values
('Pharmacovigilance','Learn how medicines are monitored for safety.','4 weeks','Beginner','🧪',
'["ADRs","Case processing","Safety databases","Signal detection","PV reporting & compliance"]',
'["PV fundamentals","Adverse Drug Reactions","Case processing workflow","Signal detection","Final practical task"]'),
('Clinical Research','Build a foundation in clinical trials and GCP.','4 weeks','Beginner','🔬',
'["Trial phases","Good Clinical Practice","Study documents","Patient safety","Clinical data basics"]',
'["Clinical research fundamentals","Trial phases","GCP and ethics","Study documents","Final practical task"]'),
('Medical Writing','Develop practical scientific and healthcare communication skills.','4 weeks','Beginner','✍️',
'["Scientific writing","Literature review","Abstracts","Referencing","Healthcare communication"]',
'["Medical writing basics","Literature review","Scientific structure","Referencing","Final writing task"]'),
('Regulatory Affairs','Explore drug regulations, submissions and compliance.','4 weeks','Beginner','📋',
'["Regulatory pathways","Dossier basics","Drug labeling","Compliance","Submission lifecycle"]',
'["Regulatory fundamentals","Drug development pathway","Dossier basics","Labeling and compliance","Final practical task"]'),
('Hospital Administration','Learn practical hospital operations and quality concepts.','4 weeks','Beginner','🏥',
'["Hospital operations","Quality management","Patient services","Documentation","Healthcare management"]',
'["Hospital operations","Patient services","Quality management","Documentation","Final practical task"]'),
('AI in Healthcare','Discover responsible AI applications across healthcare.','4 weeks','Beginner','🤖',
'["AI fundamentals","Healthcare use cases","Clinical decision support","Medical data","Responsible AI"]',
'["AI fundamentals","Healthcare use cases","Clinical decision support","Medical data","Responsible AI task"]')
on conflict (name) do update set description=excluded.description,duration=excluded.duration,level=excluded.level,icon=excluded.icon,topics=excluded.topics,modules=excluded.modules;
